on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "~1.20.2"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: |
          make tar
          for i in build/out/*.tar.gz; do
            echo ${i}
            tar -tvf ${i}
          done
      - uses: actions/upload-artifact@v3
        with:
          name: coredns
          path: build/out
          retention-days: ${{ github.event_name == 'pull_request' && 1 || 30 }}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/out/*
