on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "~1.20.2"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - id: package
        run: |
          make tar
          for i in build/out/*.tar.gz; do
            echo ${i}
            tar -tvf ${i}
          done
          echo "version=$(make get-version)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: coredns
          path: build/out
          retention-days: ${{ github.event_name == 'pull_request' && 1 || 30 }}
      - id: existing-tags
        run: |
          echo "tags=$(gh api repos/{owner}/{repo}/releases | jq '.[].tag_name')" >> $GITHUB_OUTPUT
      - name: release
        uses: softprops/action-gh-release@v1
        if: >-
          !contains(steps.existing-tags.outputs.tags, steps.package.outputs.version)
          && github.event_name != 'pull_request'
        with:
          tag_name: ${{ steps.package.outputs.version }}
          files: |
            build/out/*
